version: '3'
services:
  wiremock:
    image: wiremock/wiremock
    ports:
      - "8181:8080"
    volumes:
      - ./mappings:/home/wiremock/mappings
      - ./__files:/home/wiremock/__files
    command: --global-response-templating